SELECT 
    b.AUTHOR_ID,
    a.AUTHOR_NAME, 
    b.CATEGORY, 
    SUM(b.PRICE * s.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a
ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES s
ON b.BOOK_ID = s.BOOK_ID
WHERE TO_CHAR(s.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY b.CATEGORY, b.AUTHOR_ID, a.AUTHOR_NAME
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC;