-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, (p.PRICE * o.SUM_SALES) AS SALES
FROM PRODUCT p, (
    SELECT SUM(SALES_AMOUNT) AS SUM_SALES, PRODUCT_ID
    FROM OFFLINE_SALE 
    GROUP BY PRODUCT_ID
    ) o
WHERE p.PRODUCT_ID = o.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC