-- CAR 테이블과 DISCOUNT_PLAN 테이블을 JOIN하여, '세단' 또는 'SUV' 중 DURATION_TYPE이 '30일 이상'인 차들의 30일 기준 요금(FEE)을 미리 계산
WITH BASE_FEE AS (
    SELECT c.CAR_ID, c.CAR_TYPE,
        TRUNC(30 * c.DAILY_FEE * (1 - p.DISCOUNT_RATE / 100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON c.CAR_TYPE = p.CAR_TYPE
    WHERE 
        c.CAR_TYPE IN ('세단', 'SUV') 
        AND p.DURATION_TYPE = '30일 이상'
),

-- HISTORY 테이블에서 11월 1일~30일과 겹치는, '대여 불가능한' CAR_ID 목록
UNABLE_CAR_ID AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
        AND START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
)

-- 1번 테이블에서 2번 목록에 포함되지 않은(NOT IN) 차들만 고릅니다.
-- 최종적으로 FEE가 50만 ~ 200만 사이인 차들만 ORDER BY로 정렬합니다.
SELECT CAR_ID, CAR_TYPE, FEE
FROM BASE_FEE
WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM UNABLE_CAR_ID)
    AND FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;