-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE '%Intact%') i
JOIN (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE '%Spayed%'
    OR SEX_UPON_OUTCOME LIKE '%Neutered%') o
ON i.ANIMAL_ID = o.ANIMAL_ID
ORDER BY i.ANIMAL_ID