SELECT 
    EXTRACT(YEAR FROM o.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM o.SALES_DATE) AS MONTH,
    u.GENDER,
    COUNT(DISTINCT u.USER_ID) AS USERS
FROM USER_INFO u
JOIN ONLINE_SALE o
ON u.USER_ID = o.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM o.SALES_DATE),
    EXTRACT(MONTH FROM o.SALES_DATE), u.GENDER
ORDER BY 1, 2, 3;