-- 코드를 입력하세요
SELECT ins.NAME, ins.DATETIME
FROM (
    SELECT NAME, DATETIME, ANIMAL_ID
    FROM ANIMAL_INS
    ORDER BY DATETIME
    ) ins
LEFT JOIN ANIMAL_OUTS outs
ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE outs.DATETIME IS NULL
AND ROWNUM <= 3;