WITH DURATION_HISTORY AS (
    SELECT HISTORY_ID, CAR_ID, 
    (END_DATE - START_DATE) + 1 AS DURATION_DAYS,
        CASE WHEN 30 < (END_DATE - START_DATE) + 1 AND (END_DATE - START_DATE) + 1 >= 90
            THEN '90일 이상'
        WHEN 7 < (END_DATE - START_DATE) + 1 AND (END_DATE - START_DATE) + 1 >= 30 
            THEN '30일 이상'
        WHEN (END_DATE - START_DATE) + 1 >= 7 
            THEN '7일 이상'
        ELSE '그 외' END AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT 
    h.HISTORY_ID, 
    TRUNC(c.DAILY_FEE * h.DURATION_DAYS * (1 - (NVL(d.DISCOUNT_RATE, 0) / 100)), 0) AS FEE
FROM DURATION_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c
ON h.CAR_ID = c.CAR_ID 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
ON h.DURATION = d.DURATION_TYPE AND c.CAR_TYPE = d.CAR_TYPE
WHERE c.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC