WITH TOTAL_JULY AS (
    SELECT 
        SUM(TOTAL_ORDER) AS TOTAL_ORDER,
        FLAVOR
    FROM JULY
    GROUP BY FLAVOR
)
SELECT FLAVOR
FROM (
    SELECT f.FLAVOR, SUM(f.TOTAL_ORDER + j.TOTAL_ORDER)
    FROM FIRST_HALF f
    JOIN TOTAL_JULY j
    ON f.FLAVOR = j.FLAVOR
    GROUP BY f.FLAVOR
    ORDER BY SUM(f.TOTAL_ORDER + j.TOTAL_ORDER) DESC)
WHERE ROWNUM <= 3;