WITH ALL_HOURS AS (
    SELECT LEVEL - 1 AS HOUR
    FROM dual
    CONNECT BY LEVEL <= 24
), ANIMAL_COUNT AS (
    SELECT
        TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR,
        COUNT(*) AS CNT
    FROM ANIMAL_OUTS 
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
)

SELECT a.HOUR AS HOUR, NVL(c.CNT, 0) AS COUNT
FROM ALL_HOURS a
LEFT JOIN ANIMAL_COUNT c
ON a.HOUR = c.HOUR
ORDER BY a.HOUR