-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK b, BOOK_SALES s
WHERE b.BOOK_ID = s.BOOK_ID
AND TO_CHAR(s.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC;