-- 코드를 입력하세요
SELECT b.BOOK_ID, a.AUTHOR_NAME, TO_CHAR(b.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK b, AUTHOR a
WHERE a.AUTHOR_ID = b.AUTHOR_ID
AND b.CATEGORY = '경제'
ORDER BY b.PUBLISHED_DATE;